name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v3.5.0
      with:
        distribution: 'temurin'
        java-version: '17'
        
    #- name: Super-Linter
    #  uses: github/super-linter@v4.9.5
    
    - name: Test Gradle
      run: ./gradlew test
      
    - name: Assemble with Gradle
      run: ./gradlew assemble
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
